# Generated by Django 4.2.4 on 2024-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=55, unique=True, verbose_name='Blog Post Slug'),
        ),
    ]
